spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://userapipostgres:5439/userapipostgres?stringtype=unspecified
    username: root
    password: root
  liquibase:
    enabled: true
    change-log: classpath:db/liquibase-changelog.xml
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://userapipostgres:5439/userapipostgres?stringtype=unspecified
    user: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  cloud:
    gcp:
      sql:
        enabled: false
      firestore:
        enabled: false

cerbos:
  baseUrl: "https://cerbos-url.com"
  username: "cerbosUser"
  password: "cerbosPassword"

management:
  endpoints:
    web:
      cors:
        allowed-origins: http://localhost:4200, http://localhost:4201
        allow-credentials: true

firebase:
  credential:
    resource-path: ${sm://projects/ny-dol-wp-work-manager/secrets/firebase-config}
    api-key: ${sm://projects/ny-dol-wp-work-manager/secrets/firebase-api-key}