spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user
    user: username
    password: password

management:
  endpoints:
    web:
      cors:
        allowed-origins: http://localhost:4200, http://localhost:4201
        allow-credentials: true

firebase:
  credential:
    resource-path: ${_FIREBASE_CONFIG}
    api-key: ${_FIREBASE_API_KEY}