apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-management
  template:
    metadata:
      labels:
        app: user-management
    spec:
      containers:
        - image: us-east4-docker.pkg.dev/ny-dol-wp-work-manager/wp-docker-repo/wp-user-api
          name: user-management
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-management-postgres-postgresql # Comes from the Bitnami Postgres Helm chart installation
                  key: postgres-password
                  optional: false
          securityContext:
            runAsNonRoot: true
          ports:
            - containerPort: 8080
